### ISSUE TITLE
Player is not removed from igloo

### ISSUE THREAD

**Issue by tootyta** [titshacking/Nitro#17]
On Auto-Disconnect, the player does not get removed from an igloo 

http://prntscr.com/eo5e0o

**Comment by titshacking** [comment]
The latest two commits with the buddies online/offline seem to have this issue fixed, but I maybe wrong, I tested this issue and it seems to work fine now..

**Comment by titshacking** [comment]
This seems to be an issue with your client because it works fine for me

![screenshot_36](https://cloud.githubusercontent.com/assets/19893160/24327361/e34aac98-11ec-11e7-8242-58f974e50136.png)
![screenshot_37](https://cloud.githubusercontent.com/assets/19893160/24327362/e354f3ba-11ec-11e7-83ec-206dc0e243be.png)
![screenshot_38](https://cloud.githubusercontent.com/assets/19893160/24327363/e35562d2-11ec-11e7-8736-f4e451abb43e.png)
![screenshot_35](https://cloud.githubusercontent.com/assets/19893160/24327364/e3564346-11ec-11e7-9541-57f91c421010.png)
