### ISSUE TITLE
Spaces in puffle names / Ban Button

### ISSUE THREAD

**Issue by tootyta** [titshacking/Nitro#2]
When you try to adopt a puffle you will get the infinite loading arrow if the name of it has a space in it. There is no error shown in the server log. 

The ban button issue is where if you're an admin and you try to ban someone nothing will happen. You click the button and it says Ban Test and I click ok and nothing happens. Nothing even shows in the server log.

**Comment by titshacking** [comment]
I have applied the fix for the puffle's with commits https://github.com/titshacking/Nitro/commit/40ea3ec267893725cc3512495a11c324b566f273 https://github.com/titshacking/Nitro/commit/62cf290fe3f20ef1c32f562deb7bbd35a4dbd804as for the ban button according to the method here:

`
method handleBanButton($strData, $objClient) {
		my @arrData = split('%', $strData);
		my $intID = $arrData[5];
		return if (!looks_like_number($intID));
		my $objPlayer = $objClient->getClientByID($intID);
		return if ($objPlayer->{penguin}->{ranking}->{rank} > 4);
		if ($objClient->{penguin}->{ranking}->{isStaff}) {
			if ($objPlayer->{penguin}->{moderation}->{isBanned} eq '') {
				$self->{child}->{mysql}->updateModerationInfo($objPlayer, 'isBanned', 'PERMANENT');
				$objPlayer->sendError(603);
				$self->{child}->{sock}->handleRemoveClient($objPlayer->{sock});
			}
		}
}
`

You need to make sure that the other penguin who you're going to kick, that the rank is **NOT** more than 4. Meaning you can't kick them if they are a _staff member_. Also make sure that your penguin's **isStaff** is set to **1** in the database, the **isAdmin** I haven't really made any use to it as far as I know.

**Comment by tootyta** [comment]
Those are set correctly, I just checked the DB.

**Comment by titshacking** [comment]
![screenshot_13](https://cloud.githubusercontent.com/assets/19893160/23977221/d1bee7d2-0a12-11e7-94d3-19750afcdb0b.png)

**Player Test:**

`{"moderation":{"isBanned":"PERMANENT","isMuted":0}}`

`{"ranking": {"isStaff": "0", "isMed": "0", "isMod": "0", "isAdmin": "0", "rank": "1"}}`

Player Lynx:

`{"moderation": {"isBanned": "", "isMuted": "0"}}`

`{"ranking": {"isStaff": "1", "isMed": "0", "isMod": "0", "isAdmin": "1", "rank": "6"}}`


You're doing something wrong.
